data_ingestion:
  bucket_name: "recommender-system-mlops"
  credentials_file_name: "grand-principle-480715-v1-bbe44ac95b61.json"
  bucket_file_names:
    - "anime.csv"
    - "anime_with_synopsis.csv"
    - "animelist.csv"

model:
  embedding_size: 128
  loss: "binary_crossentropy"
  optimizer: "Adam"
  metrics: ["mae", "mse"]